### ISSUE TITLE
Project ERROR: Unknown module(s) in QT: core gui qml quick

### ISSUE THREAD

**Issue by Kabouik** [rburchell/literm#26]
I'm a bit late to the party, but I would like to try `literm` on SFOS. I understand development might have been frozen for it while Fingerterm continued, but as far as I understand we still have no 24-bit colour support in SFOS's Fingerterm (or I don't know how to make use of the feature). I also experience a lot of issues with refreshing/redrawing in Fingerterm, expecially with `TERM=xterm-256-color`, but also to a lesser extent with `TERM=xterm-color`.

Therefore I am trying to compile it on device, and I get the error in the title here. 

Should I install qt5-qtdeclarative-qtquick-devel? That means installing all these packages, and I admit that got me a little worried:

```
[nemo@Sailfish literm]$ devel-su zypper install qt5-qtdeclarative-qtquick-devel
Password: 
Loading repository data...
Reading installed packages...
Resolving package dependencies...

The following 16 NEW packages are going to be installed:
  fontconfig-devel libdrm-devel mesa-llvmpipe-libEGL mesa-llvmpipe-libEGL-devel mesa-llvmpipe-libGLESv2
  mesa-llvmpipe-libGLESv2-devel mesa-llvmpipe-libgbm mesa-llvmpipe-libglapi qml-rpm-macros qt5-qtcore-devel
  qt5-qtdeclarative-devel qt5-qtdeclarative-qtquick-devel qt5-qtgui-devel qt5-qtnetwork-devel qt5-qtsql-devel
  qt5-tools
```

**Comment by rburchell** [comment]
> I understand development might have been frozen for it while Fingerterm continued

I never really had strong intentions to replace fingerterm (though there was some consideration of doing that), I just wanted to see what was possible really :)

> Therefore I am trying to compile it on device, and I get the error in the title here.

Yeah, don't try build it on device. You'll need an SDK.

> Should I install qt5-qtdeclarative-qtquick-devel? That means installing all these packages, and I admit that got me a little worried:

Rightfully so: you definitely don't want mesa's EGL/GL stack, as that will conflict/replace with hybris' version, which will leave you very unhappy, with a device that can no longer run a UI.

I don't think there's a workaround for that, other than using an SDK, unfortunately. mesa's headers are used at build time to create binaries, but then on device, mesa is typically not used.

**Comment by Kabouik** [comment]
Uh, for once my instinct was not completely wrong then!

I need to free some space on my computer before I can install the SDK, but I certainly will. Alternatively, can this be built using OBS? I have no experience with it but that seems like a convenient way to build packages for SFOS.

literm seems like a nice improvement compared to Fingerterm because of 24-bit colours for instance, and perhaps it doesn't suffer the refreshing issues. We have Fingerterm 1.3.11 on device while what I find on the corresponding git.sailfishos repo is 1.3.2 so I don't exactly know what has been added since then, but I don't think we have 24-bit colours yet.

**Comment by rburchell** [comment]
OBS builds should work fine I would think, yes. I think that @pvuorela may have even had it packaged up somewhere, at some point...

There's still packaging over in https://github.com/rburchell/literm/blob/master/rpm/literm.spec that should work out OK from what I remember :)

**Comment by Kabouik** [comment]
Managed to build it, my first build using OBS! Thanks. :] Do you allow me to distribute it on Openrepos? Of course I would make it clear that you developed it, not me. and that development is frozen for now.

Seeing all the automation done in the .spec file, it is clear that there is no way I can do that for many other packages unless .spec files are available. Building on device may break my device, but given my limited programming knowledge, it's easier to write a simple .spec file that doesn't have to handle the compilation, sadly.

Back to literm, it works well on SFOS but I don't think I am getting 24-bit colours in it. I tried with `xterm-color`, `xterm-256color` (broken refresh) and `linux` (partly broken refresh) as `$TERM`. Should I try something else?

**Comment by rburchell** [comment]
> Managed to build it, my first build using OBS! Thanks. :] Do you allow me to distribute it on Openrepos? 

Sure, you can do whatever you like with it :)

> Building on device may break my device, but given my limited programming knowledge, it's easier to write a simple .spec file that doesn't have to handle the compilation, sadly.

It looks intimidating, but it's not that bad really. With some reading, and practice, you'll be packaging like a pro in no time :)

> Back to literm, it works well on SFOS but I don't think I am getting 24-bit colours in it

Hmm, well, my memory's pretty fuzzy since it's been a long while since I touched this, but a few things to check: run literm from fingerterm, or check journal, and see if there's any output that looks interesting. For example, you might see "got malformed extended SGR:" or something like that.

I've taken a quick test of it now, and I think I broke it subsequently after adding it. I've pushed a cleanup (and fix) now; please try that and see how it goes.

**Comment by Kabouik** [comment]
Thanks!

I didn't see much in stderr from Fingerterm, will try your update.

That's weird, I'm getting a "file name too long" error on OBS now while it worked with the previous commit:

```
literm.armv7hl: W: no-changelogname-tag
literm.src: W: no-changelogname-tag
There is no %changelog tag in your spec file. To insert it, just insert a
'%changelog' in your spec file and rebuild it.
literm.src: W: invalid-url Source0: literm-1.3.2+master.20180313075647.39f3f98.tar.gz
The value should be a valid, public HTTP, HTTPS, or FTP URL.
literm.armv7hl: W: filename-too-long-for-joliet literm-1.3.2+master.20180313075647.39f3f98-1.6.1.jolla.armv7hl.rpm
This filename is too long to fit on a joliet filesystem (limit is 64 unicode
chars).
2 packages and 0 specfiles checked; 0 errors, 4 warnings
```
https://build.sailfishos.org/package/show/home:kabouik/literm

**Comment by rburchell** [comment]
The actual warnings are hidden in the build log (click the red "failed" link), those are just some "this might be bad" warnings.

```
[   73s] terminal.cpp: In function 'Parser::TextAttributes convert(TermChar::TextAttributes&)':
[   73s] terminal.cpp:618:15: error: 'Parser::TextAttributes' {aka 'class QFlags<Parser::TextAttribute>'} has no member named 'setFlag'; did you mean 'testFlag'?
[   73s]          attrs.setFlag(Parser::TextAttribute::BoldAttribute);
[   73s]                ^~~~~~~
[   73s]                testFlag
[   73s] terminal.cpp:621:15: error: 'Parser::TextAttributes' {aka 'class QFlags<Parser::TextAttribute>'} has no member named 'setFlag'; did you mean 'testFlag'?
[   73s]          attrs.setFlag(Parser::TextAttribute::ItalicAttribute);
[   73s]                ^~~~~~~
[   73s]                testFlag
[   73s] terminal.cpp:624:15: error: 'Parser::TextAttributes' {aka 'class QFlags<Parser::TextAttribute>'} has no member named 'setFlag'; did you mean 'testFlag'?
[   73s]          attrs.setFlag(Parser::TextAttribute::UnderlineAttribute);
[   73s]                ^~~~~~~
[   73s]                testFlag
[   73s] terminal.cpp:627:15: error: 'Parser::TextAttributes' {aka 'class QFlags<Parser::TextAttribute>'} has no member named 'setFlag'; did you mean 'testFlag'?
[   73s]          attrs.setFlag(Parser::TextAttribute::NegativeAttribute);
[   73s]                ^~~~~~~
[   73s]                testFlag
[   73s] terminal.cpp:630:15: error: 'Parser::TextAttributes' {aka 'class QFlags<Parser::TextAttribute>'} has no member named 'setFlag'; did you mean 'testFlag'?
[   73s]          attrs.setFlag(Parser::TextAttribute::BlinkAttribute);
[   73s]                ^~~~~~~
[   73s]                testFlag
```

So I assume the Qt build you are using is a pretty old one. I think that setFlag was introduced in 5.7, or 5.8 (I don't recall offhand). It's easy enough to support the "older style", so I'll just do that.

**Comment by rburchell** [comment]
See 9d6712c16949c521e1ff265d61dfbd8aa372f6d8.

**Comment by Kabouik** [comment]
Successfully built on OBS this time, thanks. 

I think I am still getting base colors:

![Screenshot_20200530_014](https://user-images.githubusercontent.com/7107523/83328217-f04f7f00-a270-11ea-816a-57ad859658a9.png)

And this is on desktop: 

![ss-2020-05-30_142816](https://user-images.githubusercontent.com/7107523/83328237-18d77900-a271-11ea-92c1-711a60933b2d.png)

**Comment by Kabouik** [comment]
But maybe I can move that to a new issue instead of this one, it's not related. I would totally understand if you do not want to invest time in `literm` anymore too, you tell me.

**Comment by rburchell** [comment]
Try the shell scripts out in the 'test' subdirectory. They print out escape codes that should trigger extended color support. Especially ./test/16bitcolors.sh for example.

**Comment by Kabouik** [comment]
This seems to work on both PC and SFOS, colour gradients are correctly showing up and they include more than just base colours (for reference, the script shows nothing in Fingerterm and even in Toeterm, despite Toeterm having a better colour support, works in Havoc that I am currently testing on SFOS before packaging it).

What is surprising is that when I run a tool like cmus in Literm, it still uses base colours just like Fingeterm, whereas Toeterm and Havoc use more advanced colours.

**Comment by Kabouik** [comment]
Could it be due to a wrong $TERM value? Just fishing here, I don't really know what I'm talking about, but I know that `xterm-256color` is causing issues in Fingerterm, and manually setting `xterm-color` solves some but probably causes others. Not sure what is best for Literm and if the default has issues as for Fingerterm.

Literm is capable of displaying more colours, as shown by the test script, but somehow applications that normally use more colours by default still use base colours in Literm (and Fingerterm, but that's expected), while other colors are used in Toeterm and, to a bigger extent, other terminals on PC.

If you think there is nothing to do about it, I am happy to put the package as is on Openrepos, but else extended colour support would be a great reason for new users to install it.

**Comment by rburchell** [comment]
I don't really know unfortunately. I've forgotten way more than I would hope about this stuff.. If you find anything out, please do let me know.

**Comment by Kabouik** [comment]
I could confirm 24bit support in `literm` using `viu`:

![Screenshot_20200603_018](https://user-images.githubusercontent.com/7107523/83650188-95d35d00-a5a7-11ea-9619-c3bf2da70bd3.png)

I'm not sure why other applications like `cmus` don't take advantage of the better color support, while `Toeterm` does despite no 24bit colour support (as far as I understand), but perhaps it's some $TERM black magic. I'll upload the package as is, I think the picture will illustrate well enough that `literm` offers some additional capabilities compared to Fingerterm/Toeterm.

**Comment by Kabouik** [comment]
It's live: https://openrepos.net/content/kabouik/literm

Thanks! 

Please let me know if you want me to change the description. Since there are still some issues with colours in Literm (for instance, the `morecolors.sh` test script does not show as many colours as it should, while `./16bit_colors.sh` and `viu` test look ok), I added a sentence about another terminal that I plan to package for SFOS which suffers none of these issues. This terminal will have no touch keyboard, so they shouldn't conflict too much anyway and should both have their own use.
